### ISSUE TITLE
node-webkit save interface don't work

### ISSUE THREAD

**Issue by dekwilde** [charlieroberts/interface.editor#3]
In the node-webkit when i click in menu > Safe interface, return this error:
Uncaught node.js Error 
TypeError: Object [object Object] has no method 'replace'
    at MenuItem.Interface.Editor.saveInterface [as click](file:///Users/dekwilde/Sites/debug/websocket/remote-control/interface-js/interface.editor-master/index.html:613:25)
    at MenuItem.handleEvent (menuitem.js:167:12)
    at IDWeakMap.global.__nwObjectsRegistry.handleEvent (node.js:912:26)

**Comment by dekwilde** [comment]
index.html line 613:
template = template.toString().replace('// place your script here', str);
Add the "toString()" and then it work,
